skillMetadata:
  sections:
    - name: Set up the connction to your Tesla powerwall
      fields:
        - name: ip_address
          type: text
          label: IP address of Tesla powerwall
          value: ""
